GET http://localhost:5069/games

###
GET http://localhost:5069/games/8

###
POST http://localhost:5069/games
Content-Type: application/json

{
    "name": "Air Force II",
    "genreId": 2,
    "price": 15.99,
    "ReleaseData": "2024-01-24"
}

###
PUT http://localhost:5069/games/4
Content-Type: application/json 

{
    "name": "Air Force I",
    "genreId": 3,
    "price": 12.99,
    "ReleaseData": "2022-03-12"
}

###
DELETE http://localhost:5069/games/6